server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: ms-client
          uri: lb://ms-client
          predicates:
            - Path=/api/clients/**
        - id: ms-account
          uri: lb://ms-account
          predicates:
            - Path=/api/accounts/**
        - id: ms-transaction
          uri: lb://ms-transaction
          predicates:
            - Path=/api/transactions/**
        - id: ms-report
          uri: lb://ms-report
          predicates:
            - Path=/api/reports/**
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true